POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhczUiLCJpZCI6IjYxYjFlMzAxODE1NDljMzBiYzgwZmIzNSIsImlhdCI6MTYzOTEzNTM5NX0.NeugVeDX0kn2H9ZNOurgkPa4HfvJsiwqNQVYHt6hLe4

{
    "title": "New blog!",
    "author": "Newton",
    "url": "https://www.new_site.com",
    "likes": 5,
    "userId": "61aa4db8854e9a51dd798770"
}