POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Very good blog!",
    "author": "Jacky Chan",
    "url": "https://www.kung_fu.com",
    "likes": 99999,
    "userId": "61aa4db8854e9a51dd798770"
}